name: tech_world
description: Adventures In Tech World, for fun and profit.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  
  redfire:
    # git: https://github.com/enspyrco/redfire.git
    path: /Users/nick/git/orgs/enspyrco/redfire
  freezed_annotation:
  json_annotation:
  redux:
  flutter_redux:
  fast_immutable_collections:

  # dio:
  googleapis: 
  googleapis_auth: 
  
  # auth 
  oauth2:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  redfire_test:
    # git: https://github.com/enspyrco/redfire_test.git
    path: /Users/nick/git/orgs/enspyrco/redfire_test
  build_runner:
  freezed:
  json_serializable:
  test:
  mockito:

flutter:
  uses-material-design: true
  fonts:
    - family:  OctoIcons
      fonts:
        - asset: fonts/OctoIcons.ttf
