/// Flutter icons OctoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OctoIcons
///      fonts:
///       - asset: fonts/OctoIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class OctoIcons {
  OctoIcons._();

  static const _kFontFam = 'OctoIcons';

  static const IconData git_pull_request =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: null);
  static const IconData issue_opened =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: null);
  static const IconData repo =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: null);
}
